# Generated by Django 4.1.5 on 2023-01-12 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_task_importance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='checkbox',
        ),
        migrations.AlterField(
            model_name='completion',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='todo.task'),
        ),
    ]
