# Generated by Django 4.1.5 on 2023-01-12 14:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_remove_task_checkbox_alter_completion_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='completed_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
